var AMOUNTINDEX = 6;
var DATEINDEX = 4;
var DATEYEARINDEX = 0;
var DATEMONTHINDEX = 1;
var DATEDAYINDEX = 2;
var DATEDAYOFWEEKINDEX = 3;
var TIMESTAMPINDEX = 5;
var CARDINDEX = 10;
var MERCHANTINDEX = 7;
var TIMELINEINDEX = 9;
var CATEGORYINDEX = 8;
var ZERO = 0;

var MONTH_MAP = {
    "Jan": 0,
    "Feb": 1,
    "Mar": 2,
    "Apr": 3,
    "May": 4,
    "Jun": 5,
    "Jul": 6,
    "Aug": 7,
    "Sep": 8,
    "Oct": 9,
    "Nov": 10,
    "Dec": 11
}

const MONTHLY_CATEGORY_LIMITS = {
    [RENT_UTILITIES_PHONE_INTERNET]: 2300,
    [INSURANCE_FINANCIAL]: 1312,  // Honda $1,117 + State Farm auto $183 + State Farm other $12

    [MEDICAL_PHARMACY]: 200,
    [GROCERY]: 500,
    [RESTAURANTS_FOOD_DRINK]: 200,
    [BAKERY_COFFEE_SHOPS]: 50,

    [ENTERTAINMENT_EVENTS]: 75,
    [SPORTS_RECREATION]: 275,
    [DONATIONS_CHARITY]: 50,

    [ONLINE_RETAIL_MARKETPLACE]: 325,
    [RETAIL_SHOPPING]: 275,
    [HOME_IMPROVEMENT_HARDWARE]: 175,
    [OTHER]: 100,

    [GAS_AUTOMOTIVE]: 75,
    [TRANSPORTATION_TRAVEL]: 250,

    [CAREER_GROWTH]: 200,
    [TEMPORARY_UNCATEGORIZED]: 25,
};

const INDIVIDUAL_CATEGORY_LIMITS = {
    [RENT_UTILITIES_PHONE_INTERNET]: 2300,  // fixed household bill
    [INSURANCE_FINANCIAL]: 1312,            // fixed household bill — updated

    [MEDICAL_PHARMACY]: 25,
    [GROCERY]: 175,
    [RESTAURANTS_FOOD_DRINK]: 130,
    [BAKERY_COFFEE_SHOPS]: 30,

    [ENTERTAINMENT_EVENTS]: 50,
    [SPORTS_RECREATION]: 155,
    [DONATIONS_CHARITY]: 15,

    [ONLINE_RETAIL_MARKETPLACE]: 165,
    [RETAIL_SHOPPING]: 115,
    [HOME_IMPROVEMENT_HARDWARE]: 65,
    [OTHER]: 75,

    [GAS_AUTOMOTIVE]: 50,
    [TRANSPORTATION_TRAVEL]: 55,
    [CAREER_GROWTH]: 200,

    [TEMPORARY_UNCATEGORIZED]: 25,
};

const SPENDING_BUDGET_PER_MONTH = 5200;